name: ğŸ† Update Snapshots
on: workflow_dispatch

jobs:
  updatesnapshots:
    name: ğŸ† Update Snapshots
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸  Checkout Repo
        uses: actions/checkout@v3

      - name: â” Setup Dode
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download Deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ğŸ“¥ Install Playwright Browsers
        run: npx playwright install --with-deps 

      - name: ğŸ­ Run Playwright
        run: npm run playwright  --update-snapshots

      - name: âœ¨ Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] Update Snapshots"
