name: ğŸ† Update Snapshots
on: workflow_dispatch

jobs:
  updatesnapshots:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸  Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ğŸ“¥ Install playwright browsers
        run: npx playwright install --with-deps 

      - name: ğŸ­ Run playwright
        run: npm run playwrighti --update-snapshots

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] Update Snapshots"
